### PR TITLE
update PR to latest master

### PR DESCRIPTION
**Pull request by cenit**

### CODE REVIEW

**Comment by vsaw** [comment]
@cenit Thanks for the PR, sorry I only saw it now.

I will first need to fix https://github.com/opendatacam/opendatacam/issues/607 before I can test this one here, but since I've been working with upstream version of Darknet during the development of this, I don't expect any issues and hope to merge this soon!

**Comment by cenit** [comment]
no problem. Your feedback will be very welcome, and please expect a merge on our side after all this waiting and your efforts. I hope darknet can be integrated well enough from upstream going on reducing the customizations needed on your side

**Comment by vsaw** [comment]
The main issue I'm facing right now is on Docker and NVIDIA. Things broke after updating to JetPack 5. Darknet itself does not seem to be the problem, rather the Docker environment.

Regarding maintaining a separate fork: I'd love to entirely skip our custom fork and use upstream Darknet, so that this repo can become just an blueprint/runner to create the Docker image (or ideally, there are official Darknet images available that we can use directly!).

The reason I have not yet done so is because 

1. this version of Darknet was stable enough for our purposes, so no immediate need
1. the rolling releases of Darknet, made it difficult to identify the status of the Darknet codebase (is the addition stable or a potentially breaking change?)
1. I was not aware of any ARM builds for the different Jetson nano modules and their respective HW capabilities (e.g. cdDNN Half, `-gencode` etc.

**Comment by vsaw** [comment]
@cenit I've updated our fork to the latest upstream of Darknet in #23. I will see how this works and if we will need additional changes in our fork (e.g. less verbose output during detection to keep ODC logs clean).

If all worked out well, we can close this pull request.

**Comment by cenit** [comment]
this pr was to update another pr of your own (https://github.com/AlexeyAB/darknet/pull/3723) which was under consideration for merging but unable to be accepted due to merge conflicts. Since I was not able to work on it (no permissions to maintainers) directly, i created a pr to update your pr.
Hope it's clear enough 🤣

**Comment by vsaw** [comment]
Ah! Sorry I did not get that! As we're not using the branch anymore I'm happy to just merge so you can go ahead and get the changes into upstream!

**Comment by cenit** [comment]
but now https://github.com/AlexeyAB/darknet/pull/3723 cannot be merged anymore, since the base branch does not exist anymore... anyway, I will cherry-pick your modifications and merge them upstream, closing your broken pr there

**Comment by vsaw** [comment]
Ah crap! I renamed some of the branches, and it looks like GitHub does not update the PR. I can also revert to the old name. Let me do this quickly to see if this fixes the PR.

**Comment by vsaw** [comment]
@cenit Done. The merge conflicts in https://github.com/AlexeyAB/darknet/pull/3723 are fixed now!

**Comment by cenit** [comment]
thanks. Merged also upstream

**Comment by cenit** [comment]
next topic for upstream will be improving docker, after consolidating things and making sure that everything works properly. Shall we take part of your experience in that?

**Comment by vsaw** [comment]
Sure. Let me know what you need from me 🙂

**Comment by cenit** [comment]
well, last time i used darknet on jetson it was without docker on a tx2. Much water has flown under the bridge since then...
I am trying to get merged useful PRs upstream and assessing current reliability when using docker. It looks like you encountered many problems with latest jetpack, so I might come back to you to understand your solution if not clear enough from your repository/message history. 
Please also feel free to upstream to alexeyab/darknet whatever you might think could be useful to the bigger community. Thanks again!

**Comment by vsaw** [comment]
Yeah, I had some issues with Docker on JetPack 5. Those are fixed now. You can take a look at the Dockerfile to build Darknet for Jetson Xavier NX here https://github.com/opendatacam/darknet/tree/development/docker/build/xavier

I believe they could be a base for proper Jetson support. However I believe they do need some improvements in the way we handle the Darknet build system. At the moment we use separate Makefiles to configure the as I don't know a simple way to configure the build programmatically (e.g. command line flags). Obviously this is not ideal as any change in the build system requires me to update multiple Makefiles.

If you know of a better way, that would be greatly appreciated.

**Comment by cenit** [comment]
right now Darknet is best built with cmake, and it should be controlled by command line quite completely whenever needed. Do you have any combination in mind?

**Comment by vsaw** [comment]
Could be I'm using it wrong then. I'm usually editing the Makefile directly (e.g. setting `GPU=1`) and then call `make` directly.

**Comment by cenit** [comment]
nowadays, just 

```
cmake -B build_cuda_enabled -S darknet_source_folder -DENABLE_CUDA=ON
```

and 

```
cmake -B build_cpu_only -S darknet_source_folder -DENABLE_CUDA=OFF
```

might be the base for your setup.
We also have a quite sofisticated build script in use for this kind of manipulations, totally scriptable itself from command line too. The only drawback is that it's written in powershell, so while being totally cross-compatible (we use it in CI for all OSes), it first requires an installation of Powershell under linux, so you might desire to avoid it, at least in the end when you have a clear setup in mind and you don't need any assistance in composing cmake commands

**Pull request merged**
