### PR TITLE
Fix for CUDNN_CONVOLUTION_FWD_PREFER_FASTEST issue

### PR DESCRIPTION
**Pull request by Qengineering**
Adapted convolutional_layer.c

### CODE REVIEW

**Comment by vsaw** [comment]
Hi, sorry I just saw your PR, could you please explain what issue exactly this PR is referring to? I'm not aware of any issue with CUDA at the moment. Thank you!

P.S. Please note that I based the PR against develop so we can safely test the changes before they hit master.

**Comment by Qengineering** [comment]
Dear @vsaw,

When following the [install instructions without docker](https://opendatacam.github.io/opendatacam/documentation/USE_WITHOUT_DOCKER.html), an "old" version of DarkNet is been downloaded.
```
git clone --depth 1 -b odc https://github.com/opendatacam/darknet

```
This version doesn't support cuDNN >=8.0 which is been found on the latest Jetson Nano JetPack version.
Hence this PR.

**Comment by vsaw** [comment]
I see, thanks for clarification. I will test it the upcoming days and include it in the v1.1.0 release if all works out. Thank you 🙏

**Comment by vsaw** [comment]
I finally got around to test it. Can confirm that this fixes the build error. I'll merge it into develop and run some final checks but looks good. Thank you @Qengineering for this fix!

**Pull request merged**
